# Note: For some silly reason (this is very mild word for what I actually suffered),
#       , adminer will not start if it's name is set to adminer. Probably something to do with ingress.
#      After fighting for entire day, I eventually changed the name 
#        to dbadmin.demo.wbitt.com , instead of adminer.demo.wbitt.com.
#      And, it worked!.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dbadmin
  labels:
    app: dbadmin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dbadmin
    spec:
      containers:
      - name: dbadmin
        image: adminer
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "100m"
          requests:
            cpu: 10m
    
---

apiVersion: v1
kind: Service
metadata:
  name: dbadmin
  labels:
    name: dbadmin
    app: dbadmin
spec:
  ports:
    - port: 8080
  selector:
    app: dbadmin

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dbadmin
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: dbadmin
spec:
  rules:
  - host: dbadmin.demo.wbitt.com
    http:
      paths:
      - path: /
        backend:
          serviceName: dbadmin
          servicePort: 8080

